http:
  port: ${PORT:-8080}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  profile:
    host: localhost
    paths: 
      - '/api/budgetProfile'
      - '/api/auth'
serviceEndpoints:
  profilesrv:
    url: ${PROFILE_SERVICE_URL}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - profile
    policies:
      - log:
          - action:
              message: 'profile ${PROFILE_SERVICE_URL} ${req.path} ${req.method}'
      - proxy:
          - action:
              serviceEndpoint: profilesrv